server:
  port: 8888
spring:
  application:
    name: config-server
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    prefer-ip-address: true
